### ISSUE TITLE
FTBFS with newer imagemagick

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/PythonMagick#5]
../../../pythonmagick_src/_Image.cpp: In function 'void Export_pyste_src_Image()':
../../../pythonmagick_src/_Image.cpp:254:76: error: no matches converting function 'antiAlias' to type 'bool (class Magick::Image::*)() const'
         .def("antiAlias", (bool (Magick::Image::*)() const)&Magick::Image::antiAlias)
                                                                            ^~~~~~~~~
In file included from ../../../pythonmagick_src/_Image.cpp:7:0:
/usr/include/ImageMagick-6/Magick++/Image.h:131:10: note: candidates are: bool Magick::Image::antiAlias()
     bool antiAlias(void);
          ^~~~~~~~~
/usr/include/ImageMagick-6/Magick++/Image.h:130:10: note:                 void Magick::Image::antiAlias(bool)
     void antiAlias(const bool flag_);
          ^~~~~~~~~
../../../pythonmagick_src/_Image.cpp:261:101: error: no matches converting function 'attribute' to type 'std::__cxx11::string (class Magick::Image::*)(std::__cxx11::string) const {aka class std::__cxx11::basic_string<char> (class Magick::Image::*)(class std::__cxx11::basic_string<char>) const}'
         .def("attribute", (std::string (Magick::Image::*)(const std::string) const )&Magick::Image::attribute)
                                                                                                     ^~~~~~~~~
In file included from ../../../pythonmagick_src/_Image.cpp:7:0:
/usr/include/ImageMagick-6/Magick++/Image.h:645:17: note: candidates are: std::__cxx11::string Magick::Image::attribute(std::__cxx11::string)
     std::string attribute(const std::string name_ );
                 ^~~~~~~~~
/usr/include/ImageMagick-6/Magick++/Image.h:644:10: note:                 void Magick::Image::attribute(std::__cxx11::string, std::__cxx11::string)
     void attribute(const std::string name_,const std::string value_);
          ^~~~~~~~~
../../../pythonmagick_src/_Image.cpp:316:81: error: no matches converting function 'colorMapSize' to type 'size_t (class Magick::Image::*)() const {aka unsigned int (class Magick::Image::*)() const}'
         .def("colorMapSize", (size_t (Magick::Image::*)() const)&Magick::Image::colorMapSize)
                                                                                 ^~~~~~~~~~~~
In file included from ../../../pythonmagick_src/_Image.cpp:7:0:
/usr/include/ImageMagick-6/Magick++/Image.h:204:12: note: candidates are: size_t Magick::Image::colorMapSize()
     size_t colorMapSize(void);
            ^~~~~~~~~~~~
/usr/include/ImageMagick-6/Magick++/Image.h:203:10: note:                 void Magick::Image::colorMapSize(size_t)
     void colorMapSize(const size_t entries_);
          ^~~~~~~~~~~~

**Comment by bastien-roucaries** [comment]
Done complie chain prblem

**Comment by mikayla-grace** [comment]
We confirmed that PythonMagick compiled properly against 6.9.6-2.  We are now working on getting it to compile against 7.0.3-5.
